### ISSUE TITLE
Oversized Interface Can Store Absurd Values of Fluids

### ISSUE THREAD

**Issue by UnknownSerhan** [GlodBlock/ExtendedAE#249] opened 2024-09-12 15:01 UTC
Same issue as https://github.com/GlodBlock/ExtendedAE/issues/233, I can easily reproduce the issue by doing nothing extraordinary. I am just sending water to the interface and it accepts all of it. I can also configure the interface to store max integer value of fluids. This issue doesn't happen with any other interface, only oversized one. ExtendedAE config is untouched (the oversized interface multiplier is x16)

![image](https://github.com/user-attachments/assets/60747fb9-bd44-481d-9aaa-0ecc8a542f25)

NeoForge: 21.1.42
ExtendedAE: 1.21-2.0.3

Here is a forced crash for more info: https://gist.github.com/UnknownSerhan/c0804c6decc187398a01522cdc0a84f3

**Comment by GlodBlock** [comment] 2024-09-13 13:09
i can't reproduce this issue. does this happen when only extendedae and ae installed?

**Comment by GlodBlock** [comment] 2024-11-02 08:47
it should has been fixed now

**Closed as completed by GlodBlock** 2024-11-02 08:47 UTC
Labels: fixed
